-- ============================================================
-- SCJC NDT 无损检测管理系统 - 初始化数据库脚本
-- 数据库: scjc_ndt (utf8mb4)
-- ============================================================

-- ============================================================
-- 一、部门/组织表
-- ============================================================
DROP TABLE IF EXISTS `user_project_rel`;
DROP TABLE IF EXISTS `user_role_rel`;
DROP TABLE IF EXISTS `signature_record`;
DROP TABLE IF EXISTS `report_record`;
DROP TABLE IF EXISTS `report_template`;
DROP TABLE IF EXISTS `system_image`;
DROP TABLE IF EXISTS `inspection_record`;
DROP TABLE IF EXISTS `sys_project`;
DROP TABLE IF EXISTS `sys_user`;
DROP TABLE IF EXISTS `sys_role`;
DROP TABLE IF EXISTS `sys_dept`;

CREATE TABLE `sys_dept` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `parent_id` BIGINT DEFAULT NULL COMMENT '父节点ID',
    `dept_name` VARCHAR(100) NOT NULL COMMENT '部门名称',
    `dept_type` VARCHAR(20) NOT NULL COMMENT 'COMPANY/BU/PROJECT',
    `bu_name` VARCHAR(50) DEFAULT NULL COMMENT '所属事业部(成都/重庆/新疆/长庆)',
    `sort` INT DEFAULT 0,
    `status` TINYINT DEFAULT 1 COMMENT '1启用 0禁用',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    INDEX `idx_parent_id` (`parent_id`),
    INDEX `idx_dept_type` (`dept_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部门/组织表';

-- 初始化组织数据
INSERT INTO `sys_dept` VALUES
(1, NULL, 'SCJC公司', 'COMPANY', NULL, 0, 1, NOW(), NOW(), 0),
(2, 1, '成都事业部', 'BU', '成都事业部', 1, 1, NOW(), NOW(), 0),
(3, 1, '重庆事业部', 'BU', '重庆事业部', 2, 1, NOW(), NOW(), 0),
(4, 1, '新疆事业部', 'BU', '新疆事业部', 3, 1, NOW(), NOW(), 0),
(5, 1, '长庆事业部', 'BU', '长庆事业部', 4, 1, NOW(), NOW(), 0),
(6, 1, '公司直属项目一', 'PROJECT', NULL, 5, 1, NOW(), NOW(), 0);

-- ============================================================
-- 二、角色表（6种固定角色）
-- ============================================================
CREATE TABLE `sys_role` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `role_code` VARCHAR(50) NOT NULL COMMENT '角色编码',
    `role_name` VARCHAR(50) NOT NULL COMMENT '角色名称',
    `description` VARCHAR(200) DEFAULT NULL,
    `sort` INT DEFAULT 0,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_role_code` (`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';

INSERT INTO `sys_role` VALUES
(1, 'SYSTEM_ADMIN',    '系统管理员',   '全局最高权限，管理系统配置、所有数据', 1, NOW()),
(2, 'COMPANY_ADMIN',   '公司级管理员', '管理公司直属项目，可创建事业部管理员', 2, NOW()),
(3, 'BU_ADMIN',        '事业部管理员', '管理本事业部项目，可立项、创建项目管理员', 3, NOW()),
(4, 'PROJECT_ADMIN',   '项目管理员',   '管理指定项目的检测数据和报告', 4, NOW()),
(5, 'TECHNICAL_LEADER','技术负责人',   '报告审阅签字（第一道）', 5, NOW()),
(6, 'PROJECT_MANAGER', '项目经理',     '报告最终签字（第二道）', 6, NOW());

-- ============================================================
-- 三、用户表
-- ============================================================
CREATE TABLE `sys_user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(50) NOT NULL COMMENT '用户名',
    `password` VARCHAR(200) NOT NULL COMMENT '密码(BCrypt)',
    `real_name` VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
    `phone` VARCHAR(20) DEFAULT NULL,
    `email` VARCHAR(100) DEFAULT NULL,
    `dept_id` BIGINT DEFAULT NULL COMMENT '所属部门',
    `status` TINYINT DEFAULT 1 COMMENT '1启用 0禁用',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_username` (`username`),
    INDEX `idx_dept_id` (`dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 用户角色关联
CREATE TABLE `user_role_rel` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `role_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_role` (`user_id`, `role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关联';

-- 用户项目关联
CREATE TABLE `user_project_rel` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `project_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_project` (`user_id`, `project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户项目关联';

-- 种子用户 (密码: admin123)
-- BCrypt hash generated by Spring Security BCryptPasswordEncoder
INSERT INTO `sys_user` VALUES
(1, 'admin', '$2b$10$m0kP4s9EmGihmXTMs5kCouG3FXD50PIoxg1XfHjqg1g72tCdiSHmW', '系统管理员', '13800000001', 'admin@scjc.com', 1, 1, NULL, NOW(), NOW(), 0);

INSERT INTO `user_role_rel` VALUES
(1, 1, 1);  -- admin -> 系统管理员

-- ============================================================
-- 四、项目表
-- ============================================================
CREATE TABLE `sys_project` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `project_code` VARCHAR(50) NOT NULL COMMENT '项目编号',
    `project_name` VARCHAR(200) NOT NULL COMMENT '项目名称',
    `unit_project_name` VARCHAR(200) DEFAULT NULL COMMENT '单位工程名称',
    `parent_id` BIGINT DEFAULT NULL COMMENT '父节点(事业部/上级项目)',
    `bu_name` VARCHAR(50) DEFAULT NULL COMMENT '所属事业部',
    `project_type` VARCHAR(20) NOT NULL COMMENT 'COMPANY_DIRECT/BU_SUB',
    `construction_unit` VARCHAR(200) DEFAULT NULL COMMENT '施工单位',
    `status` VARCHAR(20) DEFAULT 'PENDING' COMMENT 'PENDING/IN_PROGRESS/COMPLETED',
    `create_by` BIGINT DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_project_code` (`project_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目表';

-- ============================================================
-- 五、检测数据表
-- ============================================================
CREATE TABLE `inspection_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `project_id` BIGINT NOT NULL COMMENT '关联项目',

    -- 基础信息
    `construction_unit` VARCHAR(200) DEFAULT NULL COMMENT '施工单位',
    `weld_no` VARCHAR(100) DEFAULT NULL COMMENT '焊口编号',
    `instruction_no` VARCHAR(100) DEFAULT NULL COMMENT '指令编号',
    `instruction_date` DATE DEFAULT NULL COMMENT '指令日期',
    `inspection_method` VARCHAR(20) DEFAULT NULL COMMENT '检测方法 RT/UT/PT/MT/AUT/PA/TOFD/DR',
    `project_name` VARCHAR(200) DEFAULT NULL COMMENT '工程名称',
    `unit_project_name` VARCHAR(200) DEFAULT NULL COMMENT '单位工程名称',
    `bu_dept` VARCHAR(100) DEFAULT NULL COMMENT '所属事业部/项目部',
    `specification` VARCHAR(100) DEFAULT NULL COMMENT '规格',
    `material` VARCHAR(100) DEFAULT NULL COMMENT '材质',
    `groove_type` VARCHAR(50) DEFAULT NULL COMMENT '坡口形式',
    `position` VARCHAR(100) DEFAULT NULL COMMENT '部位',
    `welding_method` VARCHAR(100) DEFAULT NULL COMMENT '焊接方式',
    `ratio` VARCHAR(50) DEFAULT NULL COMMENT '比例',
    `inspection_standard` VARCHAR(100) DEFAULT NULL COMMENT '检测标准',
    `qualified_level` VARCHAR(50) DEFAULT NULL COMMENT '合格级别',
    `inspection_item` VARCHAR(200) DEFAULT NULL COMMENT '检测项目',
    `welder_code` VARCHAR(50) DEFAULT NULL COMMENT '焊工代号',
    `welding_dept` VARCHAR(200) DEFAULT NULL COMMENT '焊接部门',
    `inspection_length` DECIMAL(10,2) DEFAULT NULL COMMENT '检测长度(m)',
    `process_card_no` VARCHAR(100) DEFAULT NULL COMMENT '工艺卡编号',
    `sampling_instruction_no` VARCHAR(100) DEFAULT NULL COMMENT '抽检指令编号',
    `inspection_date` DATE DEFAULT NULL COMMENT '检测日期',

    -- 检测结果
    `result_level` VARCHAR(10) DEFAULT NULL COMMENT '级别 Ⅰ/Ⅱ/Ⅲ/Ⅳ',
    `inspection_conclusion` VARCHAR(20) DEFAULT NULL COMMENT '检测结论 合格/不合格',
    `unqualified_handling` VARCHAR(500) DEFAULT NULL COMMENT '不合格处理情况',

    -- 报告中缺陷
    `report_defect_position` VARCHAR(200) DEFAULT NULL COMMENT '报告中缺陷位置',
    `report_defect_nature` VARCHAR(200) DEFAULT NULL COMMENT '报告中缺陷性质',
    `report_defect_length` DECIMAL(10,2) DEFAULT NULL COMMENT '报告中缺陷长度',
    `unqualified_defect_type` VARCHAR(200) DEFAULT NULL COMMENT '不合格缺陷类型',

    -- 备注/人员
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `inspector_name` VARCHAR(50) DEFAULT NULL COMMENT '检测人员',

    -- 底片(RT)
    `box_no` VARCHAR(50) DEFAULT NULL COMMENT '箱号',
    `film_length` DECIMAL(10,2) DEFAULT NULL COMMENT '底片长度',
    `film_count` INT DEFAULT NULL COMMENT '底片张数',

    -- 文件
    `image_url` VARCHAR(500) DEFAULT NULL COMMENT '图片',
    `inspection_report_url` VARCHAR(500) DEFAULT NULL COMMENT '检测报告文件',
    `original_record_url` VARCHAR(500) DEFAULT NULL COMMENT '原始记录文件',

    -- 缺陷位置(JSON, 最多15组)
    `defect_positions` JSON DEFAULT NULL COMMENT '缺陷位置数组 [{"pos":1,"defect":"气孔","length":5.2,"level":"Ⅱ","other":"..."}]',

    -- Ⅰ-Ⅳ级缺陷统计 (底片评定用)
    `level_i` INT DEFAULT 0 COMMENT 'Ⅰ级缺陷数',
    `level_ii` INT DEFAULT 0 COMMENT 'Ⅱ级缺陷数',
    `level_iii` INT DEFAULT 0 COMMENT 'Ⅲ级缺陷数',
    `level_iv` INT DEFAULT 0 COMMENT 'Ⅳ级缺陷数',

    `create_by` BIGINT DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX `idx_project_id` (`project_id`),
    INDEX `idx_weld_no` (`weld_no`),
    INDEX `idx_inspection_method` (`inspection_method`),
    INDEX `idx_inspection_date` (`inspection_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检测数据表';

-- ============================================================
-- 六、系统图片库
-- ============================================================
CREATE TABLE `system_image` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `image_name` VARCHAR(200) NOT NULL COMMENT '图片名称',
    `image_url` VARCHAR(500) NOT NULL COMMENT '图片路径',
    `image_type` VARCHAR(50) DEFAULT NULL COMMENT 'FILM/DIAGRAM/OTHER',
    `technique_type` VARCHAR(50) DEFAULT NULL COMMENT '透照方式 双壁双影/双壁双影纵/双壁单影/单壁透照/中心透照',
    `project_id` BIGINT DEFAULT NULL COMMENT '项目专属图片(空=系统公共)',
    `upload_by` BIGINT DEFAULT NULL,
    `upload_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_technique_type` (`technique_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统图片库';

-- ============================================================
-- 七、报告模板表
-- ============================================================
CREATE TABLE `report_template` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `project_id` BIGINT DEFAULT NULL COMMENT '所属项目(空=系统模板)',
    `template_name` VARCHAR(200) NOT NULL COMMENT '模板名称',
    `template_type` VARCHAR(20) NOT NULL DEFAULT 'CUSTOM' COMMENT 'SYSTEM/CUSTOM',
    `method_type` VARCHAR(20) DEFAULT NULL COMMENT '适用检测方法 RT/UT/PT/MT...',
    `description` VARCHAR(500) DEFAULT NULL COMMENT '模板描述',
    `layout_config` JSON NOT NULL COMMENT '页面布局配置(字段位置/尺寸/绑定)',
    `create_by` BIGINT DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX `idx_template_type` (`template_type`),
    INDEX `idx_method_type` (`method_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告模板表';

-- 预设系统模板：射线检测报告（基于 PDF: JHCZT-WQ-RT-0073渡口河净化厂射线报告）
INSERT INTO `report_template` VALUES
(1, NULL, '射线检测报告（标准版）', 'SYSTEM', 'RT',
 '基于渡口河净化厂射线报告首页+附页格式。包含首页信息区、底片布置图区、缺陷记录表、签字区；附页补充缺陷详细记录',
 '{
   "pages": [
     {
       "name": "首页",
       "paper": "A4",
       "orientation": "portrait",
       "sections": [
         {
           "type": "table",
           "label": "工程信息",
           "rows": [
             [
               {"label": "工程名称", "bind": "project_name", "span": 2},
               {"label": "施工单位", "bind": "construction_unit", "span": 2}
             ],
             [
               {"label": "工程编号", "bind": "project_code", "span": 1},
               {"label": "指令编号", "bind": "instruction_no", "span": 1},
               {"label": "指令日期", "bind": "instruction_date", "span": 1},
               {"label": "检测方法", "bind": "inspection_method", "span": 1}
             ],
             [
               {"label": "规格", "bind": "specification", "span": 1},
               {"label": "材质", "bind": "material", "span": 1},
               {"label": "坡口形式", "bind": "groove_type", "span": 1},
               {"label": "焊接方式", "bind": "welding_method", "span": 1}
             ],
             [
               {"label": "检测标准", "bind": "inspection_standard", "span": 1},
               {"label": "合格级别", "bind": "qualified_level", "span": 1},
               {"label": "检测比例", "bind": "ratio", "span": 1},
               {"label": "检测长度(m)", "bind": "inspection_length", "span": 1}
             ],
             [
               {"label": "检测日期", "bind": "inspection_date", "span": 1},
               {"label": "焊工代号", "bind": "welder_code", "span": 1},
               {"label": "部位", "bind": "position", "span": 2}
             ],
             [
               {"label": "检测项目", "bind": "inspection_item", "span": 2},
               {"label": "工艺卡编号", "bind": "process_card_no", "span": 2}
             ]
           ]
         },
         {
           "type": "image-area",
           "label": "底片布置图",
           "description": "从系统图片库选择透照示意图或底片图片",
           "width": "full",
           "height": "280px",
           "accept_types": ["DIAGRAM", "FILM"],
           "multiple": true,
           "max_images": 4
         },
         {
           "type": "table",
           "label": "检测结果",
           "columns": [
             {"label": "焊口编号", "bind": "weld_no", "width": "120px"},
             {"label": "缺陷位置", "bind": "report_defect_position", "width": "100px"},
             {"label": "缺陷性质", "bind": "report_defect_nature", "width": "120px"},
             {"label": "缺陷长度(mm)", "bind": "report_defect_length", "width": "100px"},
             {"label": "评定级别", "bind": "result_level", "width": "80px"},
             {"label": "检测结论", "bind": "inspection_conclusion", "width": "80px"},
             {"label": "备注", "bind": "remark", "width": "auto"}
           ],
           "data_source": "inspection_record",
           "data_filter": "current"
         },
         {
           "type": "table",
           "label": "底片评定",
           "columns": [
             {"label": "底片张数", "bind": "film_count", "width": "100px"},
             {"label": "Ⅰ级", "bind": "level_i", "width": "80px"},
             {"label": "Ⅱ级", "bind": "level_ii", "width": "80px"},
             {"label": "Ⅲ级", "bind": "level_iii", "width": "80px"},
             {"label": "Ⅳ级", "bind": "level_iv", "width": "80px"}
           ],
           "data_source": "inspection_record",
           "data_filter": "current"
         },
         {
           "type": "signature",
           "label": "签字区",
           "signatories": [
             {"order": 0, "label": "检测人员", "role": null, "manual": true},
             {"order": 1, "label": "技术负责人", "role": "TECHNICAL_LEADER", "manual": false},
             {"order": 2, "label": "项目经理", "role": "PROJECT_MANAGER", "manual": false}
           ]
         }
       ]
     },
     {
       "name": "附页",
       "paper": "A4",
       "orientation": "portrait",
       "sections": [
         {
           "type": "header",
           "label": "射线检测报告附页",
           "style": {"fontSize": "16px", "fontWeight": "bold", "textAlign": "center"}
         },
         {
           "type": "table",
           "label": "工程信息",
           "rows": [
             [
               {"label": "工程名称", "bind": "project_name", "span": 2},
               {"label": "焊口编号", "bind": "weld_no", "span": 1},
               {"label": "检测日期", "bind": "inspection_date", "span": 1}
             ]
           ]
         },
         {
           "type": "table",
           "label": "缺陷详细记录(续)",
           "columns": [
             {"label": "位置", "bind": "defect_positions[].pos", "width": "60px"},
             {"label": "其他缺陷", "bind": "defect_positions[].defect", "width": "150px"},
             {"label": "其他缺陷及长度", "bind": "defect_positions[].length", "width": "120px"},
             {"label": "级别", "bind": "defect_positions[].level", "width": "60px"}
           ],
           "data_source": "defect_positions",
           "data_filter": "all",
           "max_rows": 15
         },
         {
           "type": "text",
           "label": "备注区",
           "content": "备注: {remark}"
         }
       ]
     }
   ],
   "image_areas": [
     {
       "area_id": "film_layout",
       "page": "首页",
       "label": "底片布置图",
       "position": {"x": "5%", "y": "45%", "width": "90%", "height": "30%"},
       "description": "拖入或选择透照方式示意图/底片图片"
     }
   ],
   "signature_flow": [
     {"order": 1, "role": "TECHNICAL_LEADER", "label": "技术负责人", "required": true},
     {"order": 2, "role": "PROJECT_MANAGER", "label": "项目经理", "required": true}
   ]
 }',
 1, NOW(), NOW(), 0);

-- ============================================================
-- 八、报告记录表
-- ============================================================
CREATE TABLE `report_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `inspection_id` BIGINT NOT NULL COMMENT '关联检测记录',
    `template_id` BIGINT NOT NULL COMMENT '关联模板',
    `report_no` VARCHAR(100) NOT NULL COMMENT '报告编号',
    `report_content` JSON DEFAULT NULL COMMENT '模板填充后的实际内容',
    `image_selections` JSON DEFAULT NULL COMMENT '用户选择的图片 [{area_id, image_id, image_url}]',
    `status` VARCHAR(20) DEFAULT 'DRAFT' COMMENT 'DRAFT/PENDING_SIGN/SIGNED/REJECTED',
    `pdf_url` VARCHAR(500) DEFAULT NULL COMMENT '导出PDF路径',
    `create_by` BIGINT DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_report_no` (`report_no`),
    INDEX `idx_inspection_id` (`inspection_id`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告记录表';

-- ============================================================
-- 九、签字记录表
-- ============================================================
CREATE TABLE `signature_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `report_id` BIGINT NOT NULL COMMENT '关联报告',
    `signatory_id` BIGINT DEFAULT NULL COMMENT '签字人',
    `signatory_role` VARCHAR(50) NOT NULL COMMENT '签字角色 TECHNICAL_LEADER/PROJECT_MANAGER',
    `sign_order` INT NOT NULL COMMENT '签字顺序(1,2)',
    `sign_status` VARCHAR(20) DEFAULT 'PENDING' COMMENT 'PENDING/SIGNED/REJECTED',
    `sign_time` DATETIME DEFAULT NULL,
    `comment` VARCHAR(500) DEFAULT NULL COMMENT '签字意见',
    `signature_image_url` VARCHAR(500) DEFAULT NULL COMMENT '签名图片',
    PRIMARY KEY (`id`),
    INDEX `idx_report_id` (`report_id`),
    INDEX `idx_signatory_id` (`signatory_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='签字记录表';
