-- ============================================================
-- SCJC NDT 无损检测管理系统 - 初始化数据库脚本
-- 数据库: scjc_ndt (utf8mb4)
-- ============================================================

CREATE DATABASE IF NOT EXISTS `scjc_ndt`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `scjc_ndt`;

-- ============================================================
-- 一、部门/组织表
-- ============================================================
DROP TABLE IF EXISTS `user_project_rel`;
DROP TABLE IF EXISTS `user_role_rel`;
DROP TABLE IF EXISTS `signature_record`;
DROP TABLE IF EXISTS `process_card`;
DROP TABLE IF EXISTS `report_record`;
DROP TABLE IF EXISTS `report_template`;
DROP TABLE IF EXISTS `system_image`;
DROP TABLE IF EXISTS `inspection_record`;
DROP TABLE IF EXISTS `sys_project`;
DROP TABLE IF EXISTS `sys_user`;
DROP TABLE IF EXISTS `sys_role`;
DROP TABLE IF EXISTS `sys_dept`;

CREATE TABLE `sys_dept` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `parent_id` BIGINT DEFAULT NULL COMMENT '父节点ID',
    `dept_name` VARCHAR(100) NOT NULL COMMENT '部门名称',
    `dept_type` VARCHAR(20) NOT NULL COMMENT 'COMPANY/BU/PROJECT',
    `bu_name` VARCHAR(50) DEFAULT NULL COMMENT '所属事业部(成都/重庆/新疆/长庆)',
    `sort` INT DEFAULT 0,
    `status` TINYINT DEFAULT 1 COMMENT '1启用 0禁用',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    INDEX `idx_parent_id` (`parent_id`),
    INDEX `idx_dept_type` (`dept_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部门/组织表';

-- 初始化组织数据
INSERT INTO `sys_dept` VALUES
(1, NULL, 'SCJC公司', 'COMPANY', NULL, 0, 1, NOW(), NOW(), 0),
(2, 1, '成都事业部', 'BU', '成都事业部', 1, 1, NOW(), NOW(), 0),
(3, 1, '重庆事业部', 'BU', '重庆事业部', 2, 1, NOW(), NOW(), 0),
(4, 1, '新疆事业部', 'BU', '新疆事业部', 3, 1, NOW(), NOW(), 0),
(5, 1, '长庆事业部', 'BU', '长庆事业部', 4, 1, NOW(), NOW(), 0),
(6, 1, '公司直属项目一', 'PROJECT', NULL, 5, 1, NOW(), NOW(), 0);

-- ============================================================
-- 二、角色表（6种固定角色）
-- ============================================================
CREATE TABLE `sys_role` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `role_code` VARCHAR(50) NOT NULL COMMENT '角色编码',
    `role_name` VARCHAR(50) NOT NULL COMMENT '角色名称',
    `description` VARCHAR(200) DEFAULT NULL,
    `sort` INT DEFAULT 0,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_role_code` (`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';

INSERT INTO `sys_role` VALUES
(1, 'SYSTEM_ADMIN',    '系统管理员',   '全局最高权限，管理系统配置、所有数据', 1, NOW()),
(2, 'COMPANY_ADMIN',   '公司级管理员', '管理公司直属项目，可创建事业部管理员', 2, NOW()),
(3, 'BU_ADMIN',        '事业部管理员', '管理本事业部项目，可立项、创建项目管理员', 3, NOW()),
(4, 'PROJECT_ADMIN',   '项目管理员',   '管理指定项目的检测数据和报告', 4, NOW()),
(5, 'TECHNICAL_LEADER','技术负责人',   '报告审阅签字（第一道）', 5, NOW()),
(6, 'PROJECT_MANAGER', '项目经理',     '报告最终签字（第二道）', 6, NOW());

-- ============================================================
-- 三、用户表
-- ============================================================
CREATE TABLE `sys_user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(50) NOT NULL COMMENT '用户名',
    `password` VARCHAR(200) NOT NULL COMMENT '密码(BCrypt)',
    `real_name` VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
    `phone` VARCHAR(20) DEFAULT NULL,
    `email` VARCHAR(100) DEFAULT NULL,
    `dept_id` BIGINT DEFAULT NULL COMMENT '所属部门',
    `status` TINYINT DEFAULT 1 COMMENT '1启用 0禁用',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_username` (`username`),
    INDEX `idx_dept_id` (`dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 用户角色关联
CREATE TABLE `user_role_rel` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `role_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_role` (`user_id`, `role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关联';

-- 用户项目关联
CREATE TABLE `user_project_rel` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `project_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_project` (`user_id`, `project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户项目关联';

-- 种子用户 (密码: admin123)
-- BCrypt hash generated by Spring Security BCryptPasswordEncoder
INSERT INTO `sys_user` VALUES
(1, 'admin', '$2b$10$m0kP4s9EmGihmXTMs5kCouG3FXD50PIoxg1XfHjqg1g72tCdiSHmW', '系统管理员', '13800000001', 'admin@scjc.com', 1, 1, NULL, NOW(), NOW(), 0);

INSERT INTO `user_role_rel` VALUES
(1, 1, 1);  -- admin -> 系统管理员

-- ============================================================
-- 四、项目表
-- ============================================================
CREATE TABLE `sys_project` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `project_code` VARCHAR(50) NOT NULL COMMENT '项目编号',
    `project_name` VARCHAR(200) NOT NULL COMMENT '项目名称',
    `unit_project_name` VARCHAR(200) DEFAULT NULL COMMENT '单位工程名称',
    `parent_id` BIGINT DEFAULT NULL COMMENT '父节点(事业部/上级项目)',
    `bu_name` VARCHAR(50) DEFAULT NULL COMMENT '所属事业部',
    `project_type` VARCHAR(20) NOT NULL COMMENT 'COMPANY_DIRECT/BU_SUB',
    `construction_unit` VARCHAR(200) DEFAULT NULL COMMENT '施工单位',
    `status` VARCHAR(20) DEFAULT 'PENDING' COMMENT 'PENDING/IN_PROGRESS/COMPLETED',
    `create_by` BIGINT DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_project_code` (`project_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目表';

-- ============================================================
-- 五、检测数据表
-- ============================================================
CREATE TABLE `inspection_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `project_id` BIGINT NOT NULL COMMENT '关联项目',

    -- 基础信息
    `construction_unit` VARCHAR(200) DEFAULT NULL COMMENT '施工单位',
    `weld_no` VARCHAR(100) DEFAULT NULL COMMENT '焊口编号',
    `instruction_no` VARCHAR(100) DEFAULT NULL COMMENT '指令编号',
    `instruction_date` DATE DEFAULT NULL COMMENT '指令日期',
    `inspection_method` VARCHAR(20) DEFAULT NULL COMMENT '检测方法 RT/UT/PT/MT/AUT/PA/TOFD/DR',
    `project_name` VARCHAR(200) DEFAULT NULL COMMENT '工程名称',
    `unit_project_name` VARCHAR(200) DEFAULT NULL COMMENT '单位工程名称',
    `bu_dept` VARCHAR(100) DEFAULT NULL COMMENT '所属事业部/项目部',
    `specification` VARCHAR(100) DEFAULT NULL COMMENT '规格',
    `material` VARCHAR(100) DEFAULT NULL COMMENT '材质',
    `groove_type` VARCHAR(50) DEFAULT NULL COMMENT '坡口形式',
    `position` VARCHAR(100) DEFAULT NULL COMMENT '部位',
    `welding_method` VARCHAR(100) DEFAULT NULL COMMENT '焊接方式',
    `ratio` VARCHAR(50) DEFAULT NULL COMMENT '比例',
    `inspection_standard` VARCHAR(100) DEFAULT NULL COMMENT '检测标准',
    `qualified_level` VARCHAR(50) DEFAULT NULL COMMENT '合格级别',
    `inspection_item` VARCHAR(200) DEFAULT NULL COMMENT '检测项目',
    `welder_code` VARCHAR(50) DEFAULT NULL COMMENT '焊工代号',
    `welding_dept` VARCHAR(200) DEFAULT NULL COMMENT '焊接部门',
    `inspection_length` DECIMAL(10,2) DEFAULT NULL COMMENT '检测长度(m)',
    `process_card_no` VARCHAR(100) DEFAULT NULL COMMENT '工艺卡编号',
    `sampling_instruction_no` VARCHAR(100) DEFAULT NULL COMMENT '抽检指令编号',
    `inspection_date` DATE DEFAULT NULL COMMENT '检测日期',

    -- 检测结果
    `result_level` VARCHAR(10) DEFAULT NULL COMMENT '级别 Ⅰ/Ⅱ/Ⅲ/Ⅳ',
    `inspection_conclusion` VARCHAR(20) DEFAULT NULL COMMENT '检测结论 合格/不合格',
    `unqualified_handling` VARCHAR(500) DEFAULT NULL COMMENT '不合格处理情况',

    -- 报告中缺陷
    `report_defect_position` VARCHAR(200) DEFAULT NULL COMMENT '报告中缺陷位置',
    `report_defect_nature` VARCHAR(200) DEFAULT NULL COMMENT '报告中缺陷性质',
    `report_defect_length` DECIMAL(10,2) DEFAULT NULL COMMENT '报告中缺陷长度',
    `unqualified_defect_type` VARCHAR(200) DEFAULT NULL COMMENT '不合格缺陷类型',

    -- 备注/人员
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `inspector_name` VARCHAR(50) DEFAULT NULL COMMENT '检测人员',

    -- 底片(RT)
    `box_no` VARCHAR(50) DEFAULT NULL COMMENT '箱号',
    `film_length` DECIMAL(10,2) DEFAULT NULL COMMENT '底片长度',
    `film_count` INT DEFAULT NULL COMMENT '底片张数',

    -- 文件
    `image_url` VARCHAR(500) DEFAULT NULL COMMENT '图片',
    `inspection_report_url` VARCHAR(500) DEFAULT NULL COMMENT '检测报告文件',
    `original_record_url` VARCHAR(500) DEFAULT NULL COMMENT '原始记录文件',

    -- 缺陷位置(JSON, 最多15组)
    `defect_positions` JSON DEFAULT NULL COMMENT '缺陷位置数组 [{"pos":1,"defect":"气孔","length":5.2,"level":"Ⅱ","other":"..."}]',

    -- Ⅰ-Ⅳ级缺陷统计 (底片评定用)
    `level_i` INT DEFAULT 0 COMMENT 'Ⅰ级缺陷数',
    `level_ii` INT DEFAULT 0 COMMENT 'Ⅱ级缺陷数',
    `level_iii` INT DEFAULT 0 COMMENT 'Ⅲ级缺陷数',
    `level_iv` INT DEFAULT 0 COMMENT 'Ⅳ级缺陷数',

    -- RT射线检测专用字段 (胶片射线报告A)
    `film_model` VARCHAR(100) DEFAULT NULL COMMENT '胶片型号',
    `film_spec` VARCHAR(100) DEFAULT NULL COMMENT '胶片规格',
    `lead_screen` VARCHAR(100) DEFAULT NULL COMMENT '铅增感屏',
    `iqi_model` VARCHAR(100) DEFAULT NULL COMMENT '像质计型号',
    `iqi_position` VARCHAR(200) DEFAULT NULL COMMENT '像质计位置',
    `required_iqi` VARCHAR(50) DEFAULT NULL COMMENT '要求达到像质指数',
    `source_type` VARCHAR(100) DEFAULT NULL COMMENT '源的种类',
    `equipment_model` VARCHAR(100) DEFAULT NULL COMMENT '设备型号',
    `tube_voltage` VARCHAR(50) DEFAULT NULL COMMENT '管电压(kV)',
    `tube_current` VARCHAR(50) DEFAULT NULL COMMENT '管电流(mA)',
    `focal_distance` VARCHAR(100) DEFAULT NULL COMMENT '焦点尺寸/焦距',
    `exposure_time` VARCHAR(50) DEFAULT NULL COMMENT '曝光时间(min)',
    `technique_type` VARCHAR(100) DEFAULT NULL COMMENT '透照方式',
    `film_processing` VARCHAR(100) DEFAULT NULL COMMENT '胶片处理',
    `development_time` VARCHAR(50) DEFAULT NULL COMMENT '显影时间(min)',
    `development_temperature` VARCHAR(50) DEFAULT NULL COMMENT '显影温度(℃)',
    `film_density_range` VARCHAR(50) DEFAULT NULL COMMENT '底片黑度范围',
    `inspection_tech_level` VARCHAR(50) DEFAULT NULL COMMENT '检测技术等级',
    `heat_treatment_status` VARCHAR(100) DEFAULT NULL COMMENT '热处理状态',
    `inspection_timing` VARCHAR(100) DEFAULT NULL COMMENT '检测时机',
    `pressure_equipment_category` VARCHAR(100) DEFAULT NULL COMMENT '承压设备类别',
    `plate_thickness` VARCHAR(50) DEFAULT NULL COMMENT '板厚(mm)',
    `iqi_value` VARCHAR(50) DEFAULT NULL COMMENT '像质指数',
    `transillumination_length` VARCHAR(50) DEFAULT NULL COMMENT '一次透照长度(mm)',
    `defect_details` VARCHAR(500) DEFAULT NULL COMMENT '缺陷情况描述',
    `inspection_count` INT DEFAULT NULL COMMENT '检测数量(道)',
    `repair_count` INT DEFAULT NULL COMMENT '返修数量(道)',
    `reinspection_count` INT DEFAULT NULL COMMENT '复探数量(道)',
    `extended_inspection_count` INT DEFAULT NULL COMMENT '扩探数量(道)',
    `first_pass_yield` VARCHAR(20) DEFAULT NULL COMMENT '一次焊接合格率',
    `final_yield` VARCHAR(20) DEFAULT NULL COMMENT '最终焊接合格率',
    `project_code` VARCHAR(50) DEFAULT NULL COMMENT '工程编号(冗余,便于报告展示)',
    `reviewer_name` VARCHAR(50) DEFAULT NULL COMMENT '审核人',
    `technical_lead_name` VARCHAR(50) DEFAULT NULL COMMENT '检测单位项目技术负责人',

    `create_by` BIGINT DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX `idx_project_id` (`project_id`),
    INDEX `idx_weld_no` (`weld_no`),
    INDEX `idx_inspection_method` (`inspection_method`),
    INDEX `idx_inspection_date` (`inspection_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检测数据表';

-- ============================================================
-- 六、工艺卡表（RT射线检测工艺参数）
-- ============================================================
CREATE TABLE `process_card` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `project_id` BIGINT NOT NULL COMMENT '关联项目',
    `process_card_no` VARCHAR(100) DEFAULT NULL COMMENT '工艺卡编号',
    `specification` VARCHAR(100) DEFAULT NULL COMMENT '规格',
    `technique_type` VARCHAR(100) DEFAULT NULL COMMENT '透照方式',
    `iqi_value` VARCHAR(50) DEFAULT NULL COMMENT '像质指数',
    `iqi_model` VARCHAR(100) DEFAULT NULL COMMENT '像质计型号',
    `equipment_model` VARCHAR(100) DEFAULT NULL COMMENT '射线机型号',
    `equipment_no` VARCHAR(100) DEFAULT NULL COMMENT '射线机编号',
    `focal_spot_size` VARCHAR(50) DEFAULT NULL COMMENT '焦点尺寸(mm)',
    `iqi_position` VARCHAR(200) DEFAULT NULL COMMENT '像质计位置',
    `focal_distance` VARCHAR(100) DEFAULT NULL COMMENT '焦距(mm)',
    `penetration_thickness` VARCHAR(50) DEFAULT NULL COMMENT '透照厚度(mm)',
    `tube_voltage` VARCHAR(50) DEFAULT NULL COMMENT '管电压(KV)',
    `exposure_time` VARCHAR(50) DEFAULT NULL COMMENT '曝光时间(min)',
    `transillumination_length` VARCHAR(50) DEFAULT NULL COMMENT '一次透照长度(mm)',
    `exposure_count` INT DEFAULT NULL COMMENT '曝光次数',
    `film_spec` VARCHAR(100) DEFAULT NULL COMMENT '胶片规格(mm)',
    `density_range` VARCHAR(50) DEFAULT NULL COMMENT '黑度范围',
    `tube_current` VARCHAR(50) DEFAULT NULL COMMENT '管电流',
    `film_type` VARCHAR(100) DEFAULT NULL COMMENT '胶片类型',
    `work_film_distance` VARCHAR(50) DEFAULT NULL COMMENT '工件-胶片距离',
    `tech_level` VARCHAR(50) DEFAULT NULL COMMENT '技术等级',
    `heat_treatment_status` VARCHAR(100) DEFAULT NULL COMMENT '热处理状态',
    `lead_screen` VARCHAR(100) DEFAULT NULL COMMENT '铅增感屏',
    `source_type` VARCHAR(100) DEFAULT NULL COMMENT '源的种类',
    `exposure_param` VARCHAR(50) DEFAULT NULL COMMENT '曝光参数(mA)',
    `transillumination_param` VARCHAR(200) DEFAULT NULL COMMENT '透照参数',
    `film_processing` VARCHAR(100) DEFAULT NULL COMMENT '胶片处理方式',
    `development_time` VARCHAR(50) DEFAULT NULL COMMENT '显影时间',
    `development_temperature` VARCHAR(50) DEFAULT NULL COMMENT '显影温度',
    `source_activity` VARCHAR(50) DEFAULT NULL COMMENT '源活度',
    `film_count` INT DEFAULT NULL COMMENT '片子张数',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `create_by` BIGINT DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX `idx_project_id` (`project_id`),
    INDEX `idx_process_card_no` (`process_card_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工艺卡表（RT射线检测工艺参数）';

-- ============================================================
-- 七、系统图片库
-- ============================================================
CREATE TABLE `system_image` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `image_name` VARCHAR(200) NOT NULL COMMENT '图片名称',
    `image_url` VARCHAR(500) NOT NULL COMMENT '图片路径',
    `image_type` VARCHAR(50) DEFAULT NULL COMMENT 'FILM/DIAGRAM/OTHER',
    `technique_type` VARCHAR(50) DEFAULT NULL COMMENT '透照方式 双壁双影/双壁双影纵/双壁单影/单壁透照/中心透照',
    `project_id` BIGINT DEFAULT NULL COMMENT '项目专属图片(空=系统公共)',
    `upload_by` BIGINT DEFAULT NULL,
    `upload_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_technique_type` (`technique_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统图片库';

-- ============================================================
-- 八、报告模板表
-- ============================================================
CREATE TABLE `report_template` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `project_id` BIGINT DEFAULT NULL COMMENT '所属项目(空=系统模板)',
    `template_name` VARCHAR(200) NOT NULL COMMENT '模板名称',
    `template_type` VARCHAR(20) NOT NULL DEFAULT 'CUSTOM' COMMENT 'SYSTEM/CUSTOM',
    `method_type` VARCHAR(20) DEFAULT NULL COMMENT '适用检测方法 RT/UT/PT/MT...',
    `description` VARCHAR(500) DEFAULT NULL COMMENT '模板描述',
    `layout_config` JSON NOT NULL COMMENT '页面布局配置(字段位置/尺寸/绑定)',
    `create_by` BIGINT DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX `idx_template_type` (`template_type`),
    INDEX `idx_method_type` (`method_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告模板表';

-- 预设系统模板：射线检测报告（标准版）
INSERT INTO `report_template` VALUES
(1, NULL, '射线检测报告（标准版）', 'SYSTEM', 'RT',
 '基于渡口河净化厂射线报告首页+附页格式。包含首页信息区、底片布置图区、缺陷记录表、签字区；附页补充缺陷详细记录',
 '{
   "pages": [
     {
       "name": "首页",
       "paper": "A4",
       "orientation": "portrait",
       "sections": [
         {
           "type": "table",
           "label": "工程信息",
           "rows": [
             [
               {"label": "工程名称", "bind": "project_name", "span": 2},
               {"label": "施工单位", "bind": "construction_unit", "span": 2}
             ],
             [
               {"label": "工程编号", "bind": "project_code", "span": 1},
               {"label": "指令编号", "bind": "instruction_no", "span": 1},
               {"label": "指令日期", "bind": "instruction_date", "span": 1},
               {"label": "检测方法", "bind": "inspection_method", "span": 1}
             ],
             [
               {"label": "规格", "bind": "specification", "span": 1},
               {"label": "材质", "bind": "material", "span": 1},
               {"label": "坡口形式", "bind": "groove_type", "span": 1},
               {"label": "焊接方式", "bind": "welding_method", "span": 1}
             ],
             [
               {"label": "检测标准", "bind": "inspection_standard", "span": 1},
               {"label": "合格级别", "bind": "qualified_level", "span": 1},
               {"label": "检测比例", "bind": "ratio", "span": 1},
               {"label": "检测长度(m)", "bind": "inspection_length", "span": 1}
             ],
             [
               {"label": "检测日期", "bind": "inspection_date", "span": 1},
               {"label": "焊工代号", "bind": "welder_code", "span": 1},
               {"label": "部位", "bind": "position", "span": 2}
             ],
             [
               {"label": "检测项目", "bind": "inspection_item", "span": 2},
               {"label": "工艺卡编号", "bind": "process_card_no", "span": 2}
             ]
           ]
         },
         {
           "type": "image-area",
           "label": "底片布置图",
           "description": "从系统图片库选择透照示意图或底片图片",
           "width": "full",
           "height": "280px",
           "accept_types": ["DIAGRAM", "FILM"],
           "multiple": true,
           "max_images": 4
         },
         {
           "type": "table",
           "label": "检测结果",
           "columns": [
             {"label": "焊口编号", "bind": "weld_no", "width": "120px"},
             {"label": "缺陷位置", "bind": "report_defect_position", "width": "100px"},
             {"label": "缺陷性质", "bind": "report_defect_nature", "width": "120px"},
             {"label": "缺陷长度(mm)", "bind": "report_defect_length", "width": "100px"},
             {"label": "评定级别", "bind": "result_level", "width": "80px"},
             {"label": "检测结论", "bind": "inspection_conclusion", "width": "80px"},
             {"label": "备注", "bind": "remark", "width": "auto"}
           ],
           "data_source": "inspection_record",
           "data_filter": "current"
         },
         {
           "type": "table",
           "label": "底片评定",
           "columns": [
             {"label": "底片张数", "bind": "film_count", "width": "100px"},
             {"label": "Ⅰ级", "bind": "level_i", "width": "80px"},
             {"label": "Ⅱ级", "bind": "level_ii", "width": "80px"},
             {"label": "Ⅲ级", "bind": "level_iii", "width": "80px"},
             {"label": "Ⅳ级", "bind": "level_iv", "width": "80px"}
           ],
           "data_source": "inspection_record",
           "data_filter": "current"
         },
         {
           "type": "signature",
           "label": "签字区",
           "signatories": [
             {"order": 0, "label": "检测人员", "role": null, "manual": true},
             {"order": 1, "label": "技术负责人", "role": "TECHNICAL_LEADER", "manual": false},
             {"order": 2, "label": "项目经理", "role": "PROJECT_MANAGER", "manual": false}
           ]
         }
       ]
     },
     {
       "name": "附页",
       "paper": "A4",
       "orientation": "portrait",
       "sections": [
         {
           "type": "header",
           "label": "射线检测报告附页",
           "style": {"fontSize": "16px", "fontWeight": "bold", "textAlign": "center"}
         },
         {
           "type": "table",
           "label": "工程信息",
           "rows": [
             [
               {"label": "工程名称", "bind": "project_name", "span": 2},
               {"label": "焊口编号", "bind": "weld_no", "span": 1},
               {"label": "检测日期", "bind": "inspection_date", "span": 1}
             ]
           ]
         },
         {
           "type": "table",
           "label": "缺陷详细记录(续)",
           "columns": [
             {"label": "位置", "bind": "defect_positions[].pos", "width": "60px"},
             {"label": "其他缺陷", "bind": "defect_positions[].defect", "width": "150px"},
             {"label": "其他缺陷及长度", "bind": "defect_positions[].length", "width": "120px"},
             {"label": "级别", "bind": "defect_positions[].level", "width": "60px"}
           ],
           "data_source": "defect_positions",
           "data_filter": "all",
           "max_rows": 15
         },
         {
           "type": "text",
           "label": "备注区",
           "content": "备注: {remark}"
         }
       ]
     }
   ],
   "image_areas": [
     {
       "area_id": "film_layout",
       "page": "首页",
       "label": "底片布置图",
       "position": {"x": "5%", "y": "45%", "width": "90%", "height": "30%"},
       "description": "拖入或选择透照方式示意图/底片图片"
     }
   ],
   "signature_flow": [
     {"order": 1, "role": "TECHNICAL_LEADER", "label": "技术负责人", "required": true},
     {"order": 2, "role": "PROJECT_MANAGER", "label": "项目经理", "required": true}
   ]
 }',
 1, NOW(), NOW(), 0);

-- 预设系统模板：胶片射线检测报告A (基于 WJ-11/WJ-12 格式)
INSERT INTO `report_template` VALUES
(2, NULL, '胶片射线报告A', 'SYSTEM', 'RT',
 '基于 WJ-11 首页 + WJ-12 附页标准格式。包含工程信息、RT参数、透照参数、底片评定、签字区及附页焊缝明细',
 '{"pageSize":"A4","pages":[{"name":"首页","sections":[{"type":"header","text":"射线检测报告","subtext":"报告编号：{reportNo}    共    页  第    页","style":{"fontSize":20,"fontWeight":"bold"}},{"type":"table","label":"工程及检测信息","rows":[[{"label":"工程名称","bind":"projectName"},{"label":"工程编号","bind":"projectCode"}],[{"label":"单位工程名称","bind":"unitProjectName"},{"label":"施工单位","bind":"constructionUnit"}],[{"label":"检测项目","bind":"inspectionItem"},{"label":"原始记录编号","bind":"instructionNo"}],[{"label":"材质规格","bind":"specification"},{"label":"承压设备类别","bind":"pressureEquipmentCategory"}],[{"label":"坡口形式","bind":"grooveType"},{"label":"热处理状态","bind":"heatTreatmentStatus"}],[{"label":"焊接方法","bind":"weldingMethod"},{"label":"检测时机","bind":"inspectionTiming"}]]},{"type":"table","label":"RT技术参数","rows":[[{"label":"胶片型号","bind":"filmModel"},{"label":"胶片规格","bind":"filmSpec"},{"label":"铅增感屏","bind":"leadScreen"},{"label":"像质计型号","bind":"iqiModel"}],[{"label":"像质计位置","bind":"iqiPosition"},{"label":"要求达到像质指数","bind":"requiredIqi"}],[{"label":"源的种类","bind":"sourceType"},{"label":"设备型号","bind":"equipmentModel"},{"label":"焦点尺寸／焦距","bind":"focalDistance"}],[{"label":"管电压","bind":"tubeVoltage"},{"label":"管电流","bind":"tubeCurrent"},{"label":"曝光时间","bind":"exposureTime"}],[{"label":"透照方式","bind":"techniqueType","colspan":4}],[{"label":"胶片处理","bind":"filmProcessing"},{"label":"显影时间","bind":"developmentTime"},{"label":"显影温度","bind":"developmentTemperature"},{"label":"底片黑度范围","bind":"filmDensityRange"}]]},{"type":"table","label":"检测结果统计","rows":[[{"label":"检测技术等级","bind":"inspectionTechLevel"},{"label":"检测比例","bind":"ratio"},{"label":"检测标准","bind":"inspectionStandard"},{"label":"合格级别","bind":"qualifiedLevel"}],[{"label":"检测数量（道）","bind":"inspectionCount"},{"label":"返修数量（道）","bind":"repairCount"},{"label":"一次焊接合格率","bind":"firstPassYield"}],[{"label":"复探数量（道）","bind":"reinspectionCount"},{"label":"扩探数量（道）","bind":"extendedInspectionCount"},{"label":"最终焊接合格率","bind":"finalYield"}]]},{"type":"image-area","label":"检测部位示意图"},{"type":"text","content":"检测结论：检测 ____ 道，合格 ____ 道，不合格 ____ 道。"},{"type":"signature","signatories":[{"label":"报告人","bind":"inspectorName"},{"label":"审核人","bind":"reviewerName"},{"label":"检测单位项目技术负责人","bind":"technicalLeadName"}]}]},{"name":"附页","sections":[{"type":"header","text":"射线检测报告（附页）","subtext":"报告编号：{reportNo}    共    页  第    页"},{"type":"table","label":"焊缝射线检测明细","headerRows":[[{"label":"单位工程名称","bind":"unitProjectName","colspan":4},{"label":"检测项目","bind":"inspectionItem","colspan":5}],[{"label":"序号","rowspan":2},{"label":"焊缝编号及底片编号","rowspan":2},{"label":"板厚（mm）","rowspan":2},{"label":"一次透照长度（mm）","rowspan":2},{"label":"像质指数","rowspan":2},{"label":"缺陷情况","colspan":2},{"label":"评定级别","rowspan":2},{"label":"备注","rowspan":2}],[{"label":"性质及长度（mm）"},{"label":"位置（mm）"}]],"columns":[{"label":"序号","field":"seq","width":50},{"label":"焊缝编号及底片编号","field":"weldNo","width":160},{"label":"板厚（mm）","field":"plateThickness","width":80},{"label":"一次透照长度（mm）","field":"transilluminationLength","width":100},{"label":"像质指数","field":"iqiValue","width":80},{"label":"性质及长度（mm）","field":"reportDefectNature","width":120},{"label":"位置（mm）","field":"reportDefectPosition","width":80},{"label":"评定级别","field":"resultLevel","width":80},{"label":"备注","field":"remark","width":100}],"dataRows":20},{"type":"signature","signatories":[{"label":"评片","bind":"inspectorName"},{"label":"审核","bind":"reviewerName"}]}]}]}',
 1, NOW(), NOW(), 0);

-- ============================================================
-- 九、报告记录表
-- ============================================================
CREATE TABLE `report_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `inspection_id` BIGINT NOT NULL COMMENT '关联检测记录',
    `template_id` BIGINT NOT NULL COMMENT '关联模板',
    `report_no` VARCHAR(100) NOT NULL COMMENT '报告编号',
    `report_content` JSON DEFAULT NULL COMMENT '模板填充后的实际内容',
    `image_selections` JSON DEFAULT NULL COMMENT '用户选择的图片 [{area_id, image_id, image_url}]',
    `status` VARCHAR(20) DEFAULT 'DRAFT' COMMENT 'DRAFT/PENDING_SIGN/SIGNED/REJECTED',
    `pdf_url` VARCHAR(500) DEFAULT NULL COMMENT '导出PDF路径',
    `create_by` BIGINT DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_report_no` (`report_no`),
    INDEX `idx_inspection_id` (`inspection_id`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告记录表';

-- ============================================================
-- 十、签字记录表
-- ============================================================
CREATE TABLE `signature_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `report_id` BIGINT NOT NULL COMMENT '关联报告',
    `signatory_id` BIGINT DEFAULT NULL COMMENT '签字人',
    `signatory_role` VARCHAR(50) NOT NULL COMMENT '签字角色 TECHNICAL_LEADER/PROJECT_MANAGER',
    `sign_order` INT NOT NULL COMMENT '签字顺序(1,2)',
    `sign_status` VARCHAR(20) DEFAULT 'PENDING' COMMENT 'PENDING/SIGNED/REJECTED',
    `sign_time` DATETIME DEFAULT NULL,
    `comment` VARCHAR(500) DEFAULT NULL COMMENT '签字意见',
    `signature_image_url` VARCHAR(500) DEFAULT NULL COMMENT '签名图片',
    PRIMARY KEY (`id`),
    INDEX `idx_report_id` (`report_id`),
    INDEX `idx_signatory_id` (`signatory_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='签字记录表';
